server:
  port: 8801
discorridor:
  env:
    app: discorridor-customer
    namespace: public
    env: dev
    name: customer-v1
    version: 1.0.0
    group: DEFAULT_GROUP
  registry:
    env:
      type: nacos
      namespace: public
      url: 192.168.0.101:8848,192.168.0.101:8849,192.168.0.101:8850
      over-time: 1000
      retry-count: 3
  consumer:
    enable: true
    filters:
      - type: token
        token-size: 1000
        token-seconds: 100
      - type: cache
        cache-size: 100
        cache-seconds: 60
    gray:
      enable: true
      ratio: 50
logging:
  level:
    root: info
    cn.jamie: debug

