### 获取consumer用户信息
GET http://localhost:8801/user/id?id=123
### 获取consumer订单信息
GET http://localhost:8801/order?id=101
### 获取consumer超时信息
GET http://localhost:8801/user/out?id=99
### 获取mix用户信息
GET http://localhost:8901/user/id?id=123
### ### 获取consumer支付信息
GET http://localhost:8801/pay?userId=123&orderId=456




### 获取provider用户信息
POST http://localhost:8080/rpc/services
Content-Type: application/json

{
  "service": "cn.jamie.discorridor.demo.api.UserService",
  "methodSign": "findById/long",
  "args": [100]
}
