server:
  port: 8080
discorridor:
  env:
    app: discorridor-provider
    namespace: public
    env: dev
    name: provider-v1
    version: 1.0.0
  registry:
    env:
      type: nacos
      namespace: public
      url: 192.168.0.101:8848,192.168.0.101:8849,192.168.0.101:8850
      over-time: 1000
      retry-count: 3
  provider:
    enable: true
    gray: false
    port: 8080

logging:
  level:
    root: info
    cn.jamie: debug
